In [ ]:
#write a program of inheritance



class org:
  def __init__(self, name, exp,dep):
    self.name = name
    self.exp = exp
    self.dep = dep

    print('(initialize emp {} :)'.format(self.name))


  def dept(self):
      print('Name of an employee {}, exp {} , dept {}'.format(self.name, self.exp, self.dep))


class empy(org):
  def __init__(self, name, exp, dep, age):
    org.__init__(self, name, exp, dep)
    self.age = age

  def dept(self):
    org.dept(self)
    print('Nmae is {}, exp is {:d}, dept is {}, age is {:d}'.format(self.name,self.exp,self.dep,self.age))


E1 = empy('rk', 12, 'devp', 25)

E1.dept()

(initialize emp rk :)
Name of an employee rk, exp 12 , dept devp
Nmae is rk, exp is 12, dept is devp, age is 25


In [ ]:

''' create a class an organisaton & add an employee to it 
making child class as dept and employee'''

#Class & Object

class Org:
  emp = 0

  def __init__(self, name , id):
    self.name = name
    self.id = id

    print('(Initilaize name of employee {})'.format(self.name))
    Org.emp += 1

  def delete(self):
        print('{} Left organization'.format(self.name))

        Org.emp -= 1

        if Org.emp == 0:
          print('{} was the last one'.format(self.name))
        else:

          print('There is still {:d} employees are working'.format(Org.emp))

  def say_hi(self):

    print('{} Joined today'.format(self.name))

  @classmethod
  def total_nos(cls):
    print('Total nos {:d}'.format(cls.emp))

E_1 = Org('ranjan', 184)
E_2 = Org('mitesh',178)
E_3 = Org('chandan', 185)
E_N = [E_1, E_2, E_3]
for i in E_N:
   i.total_nos()
E_1.delete()



(Initilaize name of employee ranjan)
(Initilaize name of employee mitesh)
(Initilaize name of employee chandan)
Total nos 3
Total nos 3
Total nos 3
ranjan Left organization
There is still 2 employees are working


In [ ]:
# Abstraction Method

''' in abstraction method we are calling module abc 
which we need to import from our library'''

from abc import ABC, abstractmethod

class Stand(ABC):
  def noofstudents(self):
    pass

class boys(Stand):
  def noofstudents(self):
    print('there are 40 boys')

class girls(Stand):
  def noofstudents(self):
    print('there are 50 girls')

students1 = boys()
students1.noofstudents()
students2 = girls()
students2.noofstudents()



there are 40 boys
there are 50 girls


In [ ]:
# Encapsulation
# class school:
#   def __init__(self):
#     self.name = 'rk'
#     self._exp = 5 
#     self.__salary = 50,000

# new_update = school()

# print(new_update.name)
# print(new_update._exp)
# print(new_update.__salary)

rk
5


AttributeError: ignored

In [ ]:
# using getters & Setters for acessing the datas

class school:
  def __init__(self):
    self.name = 'sv'
    self._exp = 5
    self.__salary = '50k'

  def getdetails(self):
    print(self._exp, self.__salary)

  def setdetails(self, exp, salary):
    self._exp = exp
    self.__salary = salary


new_tutor = school()
new_tutor.getdetails()
new_tutor.setdetails(7, '50k')
new_tutor.getdetails()


5 50k
7 50k


In [ ]:
#interface
''' formal interface that is used to compare two classes in terms of 
true or false'''

from abc import ABC, abstractmethod
class kite(ABC):
  @abstractmethod
  def fly(self):
    pass

class rombus_shape(kite):
  def fly(self):
    print('It has four sides')

k = rombus_shape()
isinstance(k, kite)

True

In [ ]:
# creating another class

class bird(ABC):
  @abstractmethod
  def fly(self):
    pass

class sparrow(bird):
  def fly(self):
    print('flying')

v = sparrow()
isinstance(v, bird)


True

In [ ]:
isinstance(v, kite)
isinstance(k, bird)

False

In [ ]:
n = int(input().strip()) ''' .strip() function removes the unwanted things from
the string we entered'''

8


In [ ]:
n = int(input().strip())   
if (n%2 == 0) and n in range(2,6):
  print('no. is even')
else:
  print('no is odd')


4
no. is even


In [ ]:
n = int(input().strip())
    
if (n%2 == 0) and n in range (2,6):
  print('Not Weird')
elif (n%2 == 0) and n in range(6,21):
  print('Weird')
elif (n%2 == 0) and n>20:
  print('Not Weird')

22
Not Weird


In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range(0 , n):
        k = i**2
        print(k)
        

4
0
1
4
9


In [ ]:
def is_leap(year):
    #leap = False
    if (year%4 ==0) or (year%400 == 0):
      leap = True
    else
      leap = False
    return leap

year = int(input())
print(is_leap(year))

2025
False


In [ ]:
def is_leap(year):
    if(year%4 == 0) or (year%400 == 0):
      leap = True
    elif(year%100 == 0):
        leap = False
    return leap
    

year = int(input())
print(is_leap(year))

2500
True


In [ ]:
# as per hackerank

def is_leap(year):
  if year%100 == 0:
    leap = False
  elif year%4 ==0:
    leap = True
  elif year%4 == 0:
    leap = True
  else:
    leap = False
  return leap

year = int(input('enter the value'))
print(is_leap(year))



enter the value1900
False


32


In [ ]:
def is_leap(year):
  if year%100==0:

    if year%400==0:
      leap= True
    else:
        leap = False

  elif year%4==0:
          leap=True
  else :
          leap=False
  return leap
year = int(input())
print(is_leap(year)) 

2032
True


In [ ]:
def is_leap(year):
    if year%100==0:
        if year%400==0:
            leap=True
        else:
            leap = False
    elif year%4==0:
        leap=True
    else :
        leap=False
    return leap
year = int(input())
print(is_leap(year))

2032
True


In [ ]:
n = int(input())
for n in range(1,n):
  print(n)

5
1
2
3
4


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4],[1,2,3,4]], int)
b = np.array([[5,6,7,7],[5,6,7,8]],int)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.floor_divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))

[[ 6  8 10 11]
 [ 6  8 10 12]]
[[-4 -4 -4 -3]
 [-4 -4 -4 -4]]
[[ 5 12 21 28]
 [ 5 12 21 32]]
[[0 0 0 0]
 [0 0 0 0]]
[[    1    64  2187 16384]
 [    1    64  2187 65536]]
[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
# solution from IIT
import numpy

n, m = [int(i) for i in input().strip().split()]
A, B = [],[]
for i in range(n) :
    A.append([int(k) for k in input().strip().split()])
for i in range(n) :
    B.append([int(k) for k in input().strip().split()])
A = numpy.array(A)
B = numpy.array(B)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
#array 
#from typing import no_type_check_decorator
# Method-2
import numpy as np
l=map(int,raw_input().split())
x=[]
y=[]
for i in range(l[0]):
    x.append(map(int,raw_input().split()))
for i in range(l[0]):
    y.append(map(int,raw_input().split()))
x=np.array(x)
y=np.array(y)
print(np.add(x, y))
print(np.substract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np_type_check_decorator.mod(x, y))
print(x**y)

NameError: ignored

In [ ]:
import numpy as np

n, m = [int(i) for i in input().strip().split()]
A, B = [], []
for i in range(n):
  A.append([int(k) for k in input().strip().split()])
for i in range(n):
  B.append([int(k) for k in input().strip().split()])

A = np.array(A)
B = np.array(B)

print(A+B)


1234


ValueError: ignored

In [ ]:
# Method-1 list comprehenssion

fruit = ['apple','banana','mango']
newlist = []

for x in fruit:
  x = x.upper()
  if "B" in x:
    newlist.append(x)

print(newlist)

['BANANA']


In [ ]:
# method-2
fruits = ['apple','Banana','Mango']
new_list = [x for x in fruits if "a" in x]
print(new_list)

['apple', 'Banana', 'Mango']


In [ ]:
fruits = ['apple','Banana','Mango']
new_list = [x.upper() for x in fruits]
print(new_list)

['APPLE', 'BANANA', 'MANGO']


In [ ]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())

print(list([i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1)  if i+j+k !=n))

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


In [ ]:
# Q find the runner-up score
''' for finding runner up score we have a list we need to first sort our list
after that we need to find the index of max element
and we minus 1 from the index of max element'''

n = int(input())
a = list(map(int, input().split()))
a.sort()
print(a[(a.index(max(a)))-1])


5
1 2 3 3 5 6
5


In [ ]:
name = str(input())
score = int(input())
a= []
a.append([name,score])
print(a)

rk
23
[['rk', 23]]


In [ ]:
# Dictionaries
# we creat a dictionary and we use it as a constructor

car_info_dict = {"Brand":"ford", "model":"mustang" , "year": 1960}
print(car_info_dict)

{'Brand': 'ford', 'model': 'mustang', 'year': 1960}


In [ ]:
# "Dict{}" as a Constructor
car_model_info = dict(brand = "Tesla", Model="Model 3", Year = "2017")
print(car_model_info)

{'brand': 'Tesla', 'Model': 'Model 3', 'Year': '2017'}


In [ ]:
# we can assign value to a dict in two ways 1 as a normal dict method or we can use it as a constructor
class_rank = dict(vk = "91", sk = "93", gk = "84")

In [ ]:
print(class_rank)

{'vk': '91', 'sk': '93', 'gk': '84'}


In [ ]:
lst = class_rank.values()
print(sorted(lst))

['84', '91', '93']


In [ ]:
print(sorted(class_rank))

['gk', 'sk', 'vk']


In [ ]:
# Accesing the key and values of a dict we need to do

# get the keys of the dictionary
print(class_rank)

{'vk': '91', 'sk': '93', 'gk': '84'}


In [ ]:
# It gives us the value
key = class_rank['gk']
print(key)
# if we don't use ".get(). function then we need to use square brackets"

84


In [ ]:
# for gettign the values
# we will use ".get function along with the key name in square brckets"

values = class_rank.get('vk')# here we need to use prarantheses with the ".get()"
print(values)


91


In [ ]:
# chnage values in dictionary 
college_rank = {'cs': 98, 'ece': 92, 'me': 75}
print(college_rank)

{'cs': 98, 'ece': 92, 'me': 75}


In [ ]:
college_rank['me']= 85
print(college_rank)

{'cs': 98, 'ece': 92, 'me': 85}


In [ ]:
# Loop through a dictionary
# if need to print only keys of dictionary one by one
college_rank = {'cs': 98, 'ece': 92, 'me': 75}

for i in college_rank:
  print (i)

cs
ece
me


In [ ]:
# for printing values of a dictionary one by one
for i in college_rank:
  print(college_rank[i])

98
92
75


In [ ]:
# if we need to print keys of a dictionary
for i in college_rank:
  print(i)

cs
ece
me


In [ ]:
# for printing values of dictionary
for i in college_rank:
  print(college_rank[i])

98
92
75


In [ ]:
# we can use ".values()"

for i in college_rank.values():
  print(i)

98
92
75


In [ ]:
# for printing values from a dictionary
for i in college_rank.values():
   print(i)

98
92
75


In [ ]:
# for looping both keys & values by using .item():
# for printing both keys & values one by one

for i in college_rank.items():
  print(i)

('cs', 98)
('ece', 92)
('me', 75)


In [ ]:
for i in college_rank.items():
  print(i)

('cs', 98)
('ece', 92)
('me', 75)


In [ ]:
# check if key exists
for j in college_rank:
  if "cs" in j:
    print("cs is available")
else:
    print('invalid entry')

cs is available
invalid entry


In [ ]:
len(college_rank)

3

In [ ]:
# for adding key & values to the dictionary we need to use below mentioned syntax
# we can use multiple values
college_rank['ce']='20'

print(college_rank)

{'cs': 98, 'ece': 92, 'me': 75, 'ce': '20', ('ce', 'it', 'mt'): ('20', '10', '5')}


In [ ]:
# Removing extra items from a dictionary
# there are several methods
# ".pop()" method
college_rank.pop('ce')
print(college_rank)

{'cs': 98, 'ece': 92, 'me': 75, ('ce', 'it', 'mt'): ('20', '10', '5')}


In [ ]:
# remove the last inserted item
# we can remove the last inserted item from a dictionary by using the 
# method ".popitem()"
college_rank.popitem()
print(college_rank)

{'cs': 98}


In [ ]:
# We can use "del" method 
# removes the item with the specified key name

college_rank['me']='20'

del college_rank['me']
print(college_rank)

{'cs': 98}


In [ ]:
dict1 = college_rank
print(dict1)

{'cs': 98}


In [ ]:
class_score = dict(abhay = '45', vinay = '55', sekhar = '75')


In [ ]:
print(class_score)

{'abhay': '45', 'vinay': '55', 'sekhar': '75'}


In [ ]:
new_class_score = dict(class_score)

In [ ]:
print(class_score)

{'abhay': '45', 'vinay': '55', 'sekhar': '75'}


In [ ]:
# A dictionary contains many dictionaries are known as nested dictionries
family = {
    
    "child1":{
        
      "name": 'jill',
      "year": 2004
    },
   "child2" : {
      "name": "emil",
     "year" : 2006
    },
   "child3" : {
     "name" : "joy",
     "year" : 2008
    }

}

In [ ]:
print(family)

{'child1': {'name': 'jill', 'year': 2004}, 'child2': {'name': 'emil', 'year': 2006}, 'child3': {'name': 'joy', 'year': 2008}}


In [ ]:
# we can create a dictionary one by one and we combine them with each other
child1 = {
    "name": "emil",
    "year_1": 2008
}
child2 = {
    "name": "jil",
    "year_1": 2010
}
child3 = {
    "name":"sk",
    "year_1": 2012
}

family = {"child1" : child1,
          "child2": child2,
          "child3": child3}

print(family)

{'child1': {'name': 'emil', 'year_1': 2008}, 'child2': {'name': 'jil', 'year_1': 2010}, 'child3': {'name': 'sk', 'year_1': 2012}}


In [8]:
# Find the student with 2nd lowest grade in a class
a =[]
name = input('Enter name')
score = float(input('score'))
#n = int(input())
#a = list(map(int, input().split()))
a.append([name, score])
a.sort()
print(a[(a.index(max(a)))-1])

Enter namerk
score50
['rk', 50.0]


In [8]:


#scoresheet = []
#second_low = 0
n = int(input())
marksheet = []
for i in range(n):
  name = input('name:' )
  score = float(input('score' ))
  marksheet.append([name,score])
scoresheet= sorted(list(set([x[1] for x in marksheet])))
#print(marksheet)
  #print(scoresheet)
second_low = scoresheet[1]
low_final_list = []
for students in marksheet:
  if second_low == students[1]:
    low_final_list.append(students[0])
for student in sorted(low_final_list):
  print(student)





2
name:rk
score45
name:sk
score25
rk


In [1]:
# Method-1

if __name__ == '__main__':
  mark_sheet = []
  for _ in range(int(input())):
    #mark_sheet = []
    name = input() # we don't need to write anyting inside the parantheses
    score = float(input())
    mark_sheet.append([name,score])
  sorted_score = sorted(list([x[1] for x in mark_sheet]))
  #print(sorted_score)
  second_lowest = sorted_score[1]
  #print(second_lowest)

  low_final_list= []
  for student in mark_sheet:
    if second_lowest == student[1]:

      low_final_list.append(student[0])
  for student in sorted(low_final_list):
    print('\n',student)





5
rk
-50
sk
-50
vk
-50
mk
51
jk
-50

 jk

 rk

 sk

 vk


In [7]:
# Method - 2
# nested list hackerrank solution
# we need to create 2 lists 1 for marks and scores and 2nd one is specially for scores
# we ask user to give total how many entries he wants to give

n =int(input())
marksheet = []
scores = []
for i in range(n):
  name = input()
  score = float(input())
  marksheet.append([name,score])
  scores.append(score)
scores = sorted(set(scores))
m = scores[1]
name = []

for j in marksheet:
  if m == j[1]:
    name.append(j[0])
name.sort()

for k in name:
  print(k)

3
rk
40
sk
20
mk
30
mk


In [8]:
x =5
y= 2.0
z = -13
print(x,y,z)

5 2.0 -13


In [9]:
print(x+y)

7.0


In [10]:
print(x-y)

3.0


In [11]:
print(abs(z))

13


In [12]:
print(x**y)

25.0


In [13]:
print(bin(x))

0b101


In [14]:
print(hex(x))

0x5


In [16]:
print(x>y)

True


In [18]:
print(x==y)

False


In [17]:
print(y>=x)

False


In [19]:
a= 101.5
print(a>50)

True


In [20]:
a = True
b = False
print(a and b)

False


In [21]:
print(a or b)

True


In [22]:
a = 101.5

print(a>20 and a<50)

False


In [23]:
print(a>20 or a<50)

True


In [24]:
a += 1
print(a)

102.5


In [27]:
a /= 5
print(a)

4.1


In [28]:
a //= 2
print(a)

2.0


In [32]:
3//2

1